version: '3.8'

services:

  product-service:
    image: product-service
    #image: SaidnDone/product-service:latest
    #pull_policy: always
    ports:
      #same port as Dockerfile
      - "8084:8084"
    build:
      context: ./product-service
      dockerfile: ./Dockerfile
    #Sets the name for the container on Docker Desktop
    container_name: product-service
    #Creates a new docker profile and this will be shown in the console output
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - mongodb
    networks:
      - spring

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo/products:/data/db
      - ./init/mongo/docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    container_name: mongodb
    restart: unless-stopped
    command: mongod --auth
    networks:
      - spring

  mongo-express:
    image: mongo-express
    ports:
      - "8082:8082"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=mongoadmin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
    container_name: mongo-express-gbc
    restart: unless-stopped
    depends_on:
      - mongodb
    networks:
      - spring

networks:
  spring:
    driver: bridge